/* Generated by Together */

package cz.abclinuxu.data;


public class ArticleRecord extends Record {
    /**
     * @supplierCardinality 1
     * @clientCardinality 1..*
     */
    private Article lnkArticle;
}
