/* Generated by Together */

package cz.abclinuxu.data;

public class HardwareRecord extends Record {
    /**
     * @clientCardinality 1..*
     * @supplierCardinality 0..1
     */
    private Make lnkMake;
}
