/* Generated by Together */

package cz.abclinuxu.data;

public class Item extends GenericObject {
    /**
     * @supplierCardinality 1
     * @clientCardinality 0..*
     */
    private Category lnkCategory;
}
