/* Generated by Together */

package cz.abclinuxu.data;

public class PollChoice {
    protected int id;
    protected String text;
    protected int count;

    /**
     * @clientCardinality 1
     * @supplierCardinality 1..*
     */
    private Poll lnkSurvey;
}
