/* Generated by Together */

package cz.abclinuxu.data;

public class Record extends GenericObject {
    /**
     * @supplierCardinality 1
     * @clientCardinality 0..*
     */
    private Item lnkItem;
}
