/* Generated by Together */

package cz.abclinuxu.data;

public class SoftwareRecord extends Record {
    /**
     * @supplierCardinality 0..1
     * @clientCardinality 1..*
     */
    private Make lnkMake;
}
