/* Generated by Together */

package abc;

public class Item extends GenericObject {
    /**
     * @supplierCardinality 1
     * @clientCardinality 0..* 
     */
    private Category lnkCategory;
    protected int owner;
    protected Date updated;
    protected String data;
}
