/* Generated by Together */

package abc;

public class Link extends GenericObject {
    protected String text;
    protected String url;

    /**
     * @clientCardinality 1
     * @supplierCardinality 1 
     */
    private Server lnkServer;
}
