/* Generated by Together */

package abc;

public class PollChoice {
    protected int id;
    protected String text;
    protected int count;

    /**
     * @clientCardinality 1
     * @supplierCardinality 1..* 
     */
    private Poll lnkSurvey;
}
