/* Generated by Together */

package abc;

public class User extends GenericObject {
    public boolean isPasswordValid(String pass) {
    }

    protected String login;
    protected String name;
    protected String email;
    protected String password;
}
