/* Generated by Together */

package abc;

public class User {
    public boolean isPasswordValid(String pass) {
    }

    private int id;
    private String login;
    private String name;
    private String email;
    private String password;
}
